# -*- coding: utf-8 -*-
"""BANA7075GenerateSparkSyncData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axthNRjs5B2WvrPokaAP8yxq93XGaNyW
"""

# Run this if you don't have pandas or numpy installed
# !pip install pandas numpy

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

def generate_sparksync_clinical_dataset(n=500):
    # --- 1. Expanded Clinical Constants ---
    # Core Diagnoses
    mh_dx = ['MDD', 'GAD', 'PTSD', 'Bipolar I', 'Bipolar II', 'OCD', 'Schizoaffective']

    # Substance Use Disorders (SUD)
    sud_dx = ['SUD-Alcohol', 'SUD-Cannabis', 'SUD-Opiate', 'SUD-Amphetamine', 'Polysubstance Use']

    # Personality Disorders (Target ~10% of patients)
    personality_dx = ['BPD', 'Avoidant PD', 'Dependent PD', 'Narcissistic PD', 'ASPD']

    # Expanded Modalities
    modalities = [
        'ERP (Exposure Response Prevention)', 'RO-DBT', 'Standard DBT',
        'Mentalization-Based Treatment (MBT)', 'Psychodynamic Therapy',
        'Transitional Life Skills', 'CBT', 'EMDR', 'Addictions Recovery (12-Step)',
        'Addictions Recovery (SMART)', 'Somatic Experiencing'
    ]

    data = []
    for i in range(n):
        # --- 2. Diagnosis Logic (The 10% Rule) ---
        # Pick 1-4 diagnoses total
        p_val = random.random()
        current_patient_dx = []

        if p_val < 0.10: # 10% get a Personality Disorder
            current_patient_dx.append(random.choice(personality_dx))

        # Add 1-2 Mental Health or SUD diagnoses
        current_patient_dx.extend(random.sample(mh_dx + sud_dx, random.randint(1, 2)))

        # Ensure at least 5 diagnosis slots are filled (for the 10 slots requirement)
        dx_padded = current_patient_dx + [None] * (10 - len(current_patient_dx))

        # --- 3. Weighted Modality Logic ---
        # If OCD is present, prioritize ERP/RO-DBT
        # If PD is present, prioritize MBT/Psychodynamic
        patient_priorities = []
        if 'OCD' in current_patient_dx:
            patient_priorities = ['ERP (Exposure Response Prevention)', 'RO-DBT']
        elif any(pd in current_patient_dx for pd in personality_dx):
            patient_priorities = ['Mentalization-Based Treatment (MBT)', 'Psychodynamic Therapy']

        # Fill remaining slots from the general list
        remaining_needed = 5 - len(patient_priorities)
        available_modalities = [m for m in modalities if m not in patient_priorities]
        patient_priorities.extend(random.sample(available_modalities, remaining_needed))

        # --- 4. Patient Record Construction ---
        patient = {
            'mrn': f"MRN-{random.randint(100000, 999999)}",
            'age': np.random.randint(18, 85),
            'gender': random.choice(['Male', 'Female', 'Non-binary']),
            'primary_diagnosis': current_patient_dx[0],
            'secondary_diagnosis': current_patient_dx[1] if len(current_patient_dx) > 1 else 'None',

            # Clinical Needs Weights
            'priority_1': patient_priorities[0],
            'priority_2': patient_priorities[1],
            'priority_3': patient_priorities[2],
            'priority_4': patient_priorities[3],
            'priority_5': patient_priorities[4],

            # Life Stage & Motivation
            'life_stage': 'Emerging Adult' if 18 <= i <= 25 else 'Adult',
            'motivation': random.choice(['Internally driven', 'Mixed', 'Family pressures']),
            'transition_focus': 'Strong Treatment' if random.random() > 0.3 else 'Life Skills/Transitional',

            # Coordinator Feedback
            'coordinator_comfort': round(np.random.uniform(3.5, 5.0), 1),
            'last_elected_program': f"Facility_{random.randint(1, 50)}"
        }

        # Add the 10 diagnosis columns
        for idx, dx in enumerate(dx_padded):
            patient[f'diagnosis_{idx+1}'] = dx

        data.append(patient)

    df = pd.DataFrame(data)
    df.to_csv('sparksync_clinical_data_v2.csv', index=False)
    return df

# Run the generation
df_final = generate_sparksync_clinical_dataset(500)
print("✅ SparkSync v2 Dataset Generated with Personality Disorder & Specialized Modality Logic.")

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

def generate_sparksync_complete_v2(n=500):
    # 1. Setup Constants
    mh_dx = ['MDD', 'GAD', 'PTSD', 'Bipolar I', 'Bipolar II', 'OCD', 'Schizoaffective']
    sud_dx = ['SUD-Alcohol', 'SUD-Cannabis', 'SUD-Opiate', 'SUD-Amphetamine', 'Polysubstance Use']
    personality_dx = ['BPD', 'Avoidant PD', 'Dependent PD', 'Narcissistic PD', 'ASPD']
    modalities = ['ERP', 'RO-DBT', 'Standard DBT', 'MBT', 'Psychodynamic', 'Life Skills', 'CBT', 'EMDR']

    data = []
    for i in range(n):
        # Personality Disorder Logic (10%)
        current_dx = [random.choice(personality_dx)] if random.random() < 0.10 else [random.choice(mh_dx)]
        current_dx.extend(random.sample(mh_dx + sud_dx, 2))

        # Modality Logic
        p = ['ERP', 'RO-DBT'] if 'OCD' in current_dx else ['MBT', 'Psychodynamic'] if any(x in current_dx for x in personality_dx) else random.sample(modalities, 2)
        p.extend(random.sample([m for m in modalities if m not in p], 3))

        patient = {
            'mrn': f"MRN-{random.randint(100000, 999999)}",
            'name': f"Patient_{i}",
            'age': np.random.randint(18, 85),
            'primary_diagnosis': current_dx[0],
            'priority_1': p[0],
            'priority_2': p[1],
            'transition_focus': 'Strong Treatment' if random.random() > 0.3 else 'Life Skills',
            'coordinator_comfort': round(np.random.uniform(3.5, 5.0), 1)
        }
        data.append(patient)

    # CREATE THE DATAFRAME
    df = pd.DataFrame(data)

    # 2. INJECT DIRTY DATA (Now 'df' is defined in this scope!)
    df.loc[0, 'age'] = 155
    df.loc[1, 'mrn'] = np.nan
    df.loc[2, 'primary_diagnosis'] = None
    df.loc[3, 'transition_focus'] = ""
    df.loc[4, 'mrn'] = "ERROR_999_###"

    # 3. SAVE
    df.to_csv('sparksync_disposition_dirty_v2.csv', index=False)
    print("✅ Success! 'sparksync_disposition_dirty_v2.csv' created with clinical logic and 5 errors.")
    return df

# RUN THE FUNCTION
df_final = generate_sparksync_complete_v2(500)

from google.colab import files

# This triggers the browser download for your dirty dataset
files.download('sparksync_disposition_dirty_v2.csv')

# Sample 'Fix' for your Pull Request
import pandas as pd
df = pd.read_csv('sparksync_disposition_dirty_v2.csv')

# Remove impossible ages and missing MRNs
df_clean = df[(df['age'] < 110) & (df['mrn'].notna())]

df_clean.to_csv('sparksync_disposition_CLEAN.csv', index=False)
print("Data cleaned for RAG ingestion.")

# Load the dirty data we just created
df_dirty = pd.read_csv('sparksync_disposition_dirty_v2.csv')

# --- THE CLEANING GATE ---
# 1. Filter out impossible ages (Must be < 110)
# 2. Remove rows where MRN is missing (Critical ID)
# 3. Remove rows where Primary Diagnosis is missing
df_clean = df_dirty[
    (df_dirty['age'] < 110) &
    (df_dirty['mrn'].notna()) &
    (df_dirty['primary_diagnosis'].notna())
].copy()

# Save the cleaned version
df_clean.to_csv('sparksync_disposition_CLEAN.csv', index=False)

print(f"✅ Data Cleaned! Removed {len(df_dirty) - len(df_clean)} invalid records.")

from google.colab import files

# Download the Dirty version (for your 'Issue' demonstration)
files.download('sparksync_disposition_dirty_v2.csv')

# Download the Clean version (for your 'ML Training' demonstration)
files.download('sparksync_disposition_CLEAN.csv')

